module.exports = {
    flyinghearts: "",
    load: "",
    verified: "",
    error: "",
    info: "",
    music1: "",
    queue: "",
    success: "",
    music: "",
    fun: "",
    chatbot: "",
    image: "",
    anime: "",
    nsfw: "",
    other: "",
    diskspin: "",
    owner: "",
    buttons: ""
}
